models/gign_dead.mdl
models/leet_dead.mdl
sound/windy.wav
sprites/Tele1.spr
gfx/env/2desertdn.tga
gfx/env/2desertbk.tga
gfx/env/2desertft.tga
gfx/env/2desertlf.tga
gfx/env/2desertrt.tga
gfx/env/2desertup.tga