FROM debian:jessie

ENV START_MAP ${START_MAP}
ENV SERVER_NAME ${SERVER_NAME}
ENV MAXPLAYERS ${MAXPLAYERS}
ENV START_MONEY ${START_MONEY}
ENV BUY_TIME ${BUY_TIME}
ENV FRIENDLY_FIRE ${FRIENDLY_FIRE}
ENV MAP_AUTOKICK ${MAP_AUTOKICK}
ENV TIMELIMIT ${TIMELIMIT}
ENV MAP_MAXROUNDS ${MAP_MAXROUNDS}
ENV ROUNDTIME ${ROUNDTIME}
ENV WINLIMIT ${WINLIMIT}
ENV MAP_VOTE_RATIO ${MAP_VOTE_RATIO}
ENV MAP_FREEZETIME ${MAP_FREEZETIME}
ENV ADMIN_STEAM ${ADMIN_STEAM}
ENV MAP_AUTOTEAMBALANCE ${MAP_AUTOTEAMBALANCE}
ENV USE_VOTEMAP ${USE_VOTEMAP}
ENV RCON_PASSWORD ${RCON_PASSWORD}
ENV SERVER_PASSWORD ${SERVER_PASSWORD}

RUN apt update && apt install lib32gcc1 -y

RUN mkdir -p /opt/
RUN mkdir -p ~/.steam/
COPY opt/. /opt/
COPY steam/. ~/.steam/

ADD hlds_run.sh /bin/hlds_run.sh
ADD extract_maps.bash /bin/extract_maps.bash

RUN chmod +x /bin/hlds_run.sh
RUN chmod +x /bin/extract_maps.bash

WORKDIR /opt/hlds

ENTRYPOINT ["/bin/hlds_run.sh"]
